version: '3'
services:
  tomb-rider:
    container_name: tomb-raider
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - tomb_network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASS
      POSTGRES_DB: POSTGRES_DB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - tombpgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tomb_network

  jaeger:
    image: jaegertracing/all-in-one:1.47
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
    networks:
      - tomb_network

networks:
  tomb_network:

volumes:
  tombpgdata:
